default:
  image: 'rust:1.42.0-buster'

variables:
  GIT_STRATEGY: clone

stages:
  - build
  - deploy

variables:
  ZOLA_VERSION: "v0.10.1"

pages:
  stage: deploy
  script:
    - curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
    - tar -xzf zola.tar.gz
    - mkdir -p ~/.cargo/bin
    - mv zola ~/.cargo/bin/
    - export PATH="~/.cargo/bin:$PATH"
    - git fetch
    - ./target/release/lmfa0 docs
  artifacts:
    paths: ['public/']
  dependencies: ['build']
  only:
    - master

test_pages:
  stage: deploy
  script:
    - curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
    - tar -xzf zola.tar.gz
    - mkdir -p ~/.cargo/bin
    - export PATH="~/.cargo/bin:$PATH"
    - mv zola ~/.cargo/bin/
    - git fetch
    - git branch --list --all
    - git fetch && git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - ./target/release/lmfa0 docs
  artifacts:
    expose_as: 'pages'
    expire_in: '1 week'
    paths: ['public/']
  dependencies: ['build']
  except:
    - master

build:
  stage: build
  script:
    - cargo build --release
    - strip target/release/lmfa0
    - size target/release/lmfa0
  artifacts:
    paths:
      - target/release/lmfa0
